spring:
  application:
    name:Spring-boot-Nyano-Application
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
